/**
 * GENERATED by scripts/gen_book_figure_assets.mjs — do not edit by hand.
 *
 * One static `require()` per reachable book figure, because Metro resolves
 * assets from string literals at build time and cannot follow a computed path.
 * Regenerate after extracting figures or editing figure-lesson-map.json.
 */
/* eslint-disable @typescript-eslint/no-require-imports */

/**
 * `sourceId/file` → the bundler's handle for that PNG.
 *
 * The two shapes are not interchangeable and both really occur: Metro's web
 * output makes each asset a module exporting `{uri, width, height}`, while
 * native `require()` yields an opaque numeric id to look up in the asset
 * registry. `bookFigureUri` is where that fork is handled.
 */
export type BookFigureAsset = number | { uri: string; width?: number; height?: number };

export const BOOK_FIGURE_ASSETS: Record<string, BookFigureAsset> = {
  'math-s1-student-book/p010.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p010.png'),
  'math-s1-student-book/p011.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p011.png'),
  'math-s1-student-book/p017.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p017.png'),
  'math-s1-student-book/p020.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p020.png'),
  'math-s1-student-book/p021.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p021.png'),
  'math-s1-student-book/p022.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p022.png'),
  'math-s1-student-book/p023.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p023.png'),
  'math-s1-student-book/p024.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p024.png'),
  'math-s1-student-book/p032.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p032.png'),
  'math-s1-student-book/p033.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p033.png'),
  'math-s1-student-book/p041.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p041.png'),
  'math-s1-student-book/p057.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p057.png'),
  'math-s1-student-book/p058.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p058.png'),
  'math-s1-student-book/p059.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p059.png'),
  'math-s1-student-book/p060.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p060.png'),
  'math-s1-student-book/p061.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p061.png'),
  'math-s1-student-book/p062.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p062.png'),
  'math-s1-student-book/p064.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p064.png'),
  'math-s1-student-book/p069.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p069.png'),
  'math-s1-student-book/p070.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p070.png'),
  'math-s1-student-book/p071.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p071.png'),
  'math-s1-student-book/p076.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p076.png'),
  'math-s1-student-book/p077.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p077.png'),
  'math-s1-student-book/p081.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p081.png'),
  'math-s1-student-book/p082.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p082.png'),
  'math-s1-student-book/p084.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p084.png'),
  'math-s1-student-book/p086.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p086.png'),
  'math-s1-student-book/p087.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p087.png'),
  'math-s1-student-book/p090.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p090.png'),
  'math-s1-student-book/p091.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p091.png'),
  'math-s1-student-book/p108.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p108.png'),
  'math-s1-student-book/p109.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p109.png'),
  'math-s1-student-book/p110.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p110.png'),
  'math-s1-student-book/p111.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p111.png'),
  'math-s1-student-book/p118.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p118.png'),
  'math-s1-student-book/p121.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p121.png'),
  'math-s1-student-book/p123.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p123.png'),
  'math-s1-student-book/p148.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p148.png'),
  'math-s1-student-book/p149.png': require('../../../knowledge-base/grade-10-math/figures/math-s1-student-book/p149.png'),
  'math-s2-student-book/p021.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p021.png'),
  'math-s2-student-book/p024.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p024.png'),
  'math-s2-student-book/p025.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p025.png'),
  'math-s2-student-book/p028.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p028.png'),
  'math-s2-student-book/p054.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p054.png'),
  'math-s2-student-book/p055.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p055.png'),
  'math-s2-student-book/p060.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p060.png'),
  'math-s2-student-book/p067.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p067.png'),
  'math-s2-student-book/p068.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p068.png'),
  'math-s2-student-book/p069.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p069.png'),
  'math-s2-student-book/p075.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p075.png'),
  'math-s2-student-book/p085.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p085.png'),
  'math-s2-student-book/p086.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p086.png'),
  'math-s2-student-book/p101.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p101.png'),
  'math-s2-student-book/p103.png': require('../../../knowledge-base/grade-10-math/figures/math-s2-student-book/p103.png'),
};

/** How many figures ship with the app. Asserted by the drift test. */
export const BOOK_FIGURE_COUNT = 54;
