/**
 * Slides HTML (Slides Maker deck) — the projector deck exported to PDF.
 *
 * Every "Slides HTML" builder in share.ts is a light, print-optimised
 * handout — correct for a worksheet or lesson plan going through a printer.
 * This one is not that: it is the projector deck itself, exported so a
 * teacher can present from PowerPoint/Google Slides/Preview when the app
 * isn't in front of the class, or file it for later. It renders the SAME
 * `ClassroomActivity` object the presenter shows on screen — same dark
 * background, same per-type accent colour, same math layout, same
 * verification badge — because a deck that looked different exported than it
 * did on the projector would just be a second, wrong deck.
 *
 * Pure logic, no React Native — kept out of share.ts deliberately, since that
 * file imports `react-native` at module scope (for Platform/Share), which
 * node:test cannot parse. Everything here only imports other pure modules,
 * so it's directly testable.
 */
import type { ActivitySlide, ClassroomActivity } from './ai/AIService.ts';
import { hasRenderableMath, mathLineToHtml, MATH_HTML_STYLES, prettifySymPy } from './mathRender.ts';

const DECK_BG = '#0D0D14';
const DECK_TEXT = '#F2F2F6';
const DECK_MUTED = '#8B8CA4';
const DECK_ACCENT = '#4F46E5';

function deckSlideAccent(type: ActivitySlide['type']): string {
  if (type === 'challenge') return '#E67E22';
  if (type === 'summary') return DECK_ACCENT;
  if (type === 'graph') return '#0EA5E9';
  if (type === 'divider') return DECK_ACCENT;
  return DECK_MUTED;
}

function deckSlideEmoji(type: ActivitySlide['type']): string {
  if (type === 'challenge') return '🔐';
  if (type === 'summary') return '🎉';
  if (type === 'graph') return '📈';
  return '🎯';
}

/** Full-bleed photo + dark gradient, or a flat accent panel with no photo — used by both the title and divider slides. */
function deckHeroLayer(mediaUrl: string | undefined): string {
  if (!mediaUrl) return '';
  return `<img class="deck-hero-img" src="${mediaUrl.replace(/"/g, '&quot;')}" alt="" />
      <div class="deck-hero-gradient"></div>`;
}

/** One content line, math-aware — mirrors MathText.tsx's decision on native. */
function deckContentLine(line: string, isEquation: boolean): string {
  if (!line.trim()) return '';
  const cls = isEquation && hasRenderableMath(line) ? 'deck-eq' : 'deck-line';
  const html = isEquation && hasRenderableMath(line) ? mathLineToHtml(line) : (line ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  return `<div class="${cls}">${html}</div>`;
}

export function buildDeckSlidesHTML(deck: ClassroomActivity, isAr: boolean): string {
  const dir = isAr ? 'rtl' : 'ltr';
  const L = (ar: string, en: string) => (isAr ? ar : en);
  const esc = (s: string) => (s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const total = deck.slides.length;

  const footer = (num: number) => `
    <div class="deck-footer">
      <span>${L('أُنشئ بواسطة إقرأ — مساعد التدريس الذكي', 'Generated by Iqra — AI Teaching Assistant')}</span>
      <span>${num} / ${total}</span>
    </div>`;

  const titleSlide = (slide: ActivitySlide, num: number) => {
    const [meta, ...rest] = slide.content.split('\n\n');
    return `<div class="deck-slide deck-title-slide">
      ${deckHeroLayer(slide.mediaUrl)}
      <div class="deck-title-content">
        <div class="deck-title-badge">IQRA</div>
        <h1 class="deck-title-main">${esc(slide.title)}</h1>
        ${meta ? `<div class="deck-title-meta">${esc(meta)}</div>` : ''}
        ${rest.length ? `<div class="deck-title-summary">${esc(rest.join(' '))}</div>` : ''}
      </div>
      ${footer(num)}</div>`;
  };

  const dividerSlide = (slide: ActivitySlide, num: number) => {
    const accent = deckSlideAccent('divider');
    return `<div class="deck-slide deck-divider-slide" style="${slide.mediaUrl ? '' : `background:${accent}`}">
      ${deckHeroLayer(slide.mediaUrl)}
      <div class="deck-divider-content">
        <h1 class="deck-divider-title">${esc(slide.title)}</h1>
        ${slide.content ? `<div class="deck-divider-subtitle">${esc(slide.content)}</div>` : ''}
      </div>
      ${footer(num)}</div>`;
  };

  const graphSlide = (slide: ActivitySlide, num: number) => {
    const accent = deckSlideAccent('graph');
    const commands = slide.graphCommands ?? [];
    const [context] = slide.content.split('\n\n');
    return `<div class="deck-slide">
      <div class="deck-header" style="border-color:${accent}44">
        <span class="deck-emoji">📈</span>
        <span class="deck-eyebrow" style="color:${accent}">${esc(slide.title)}</span>
      </div>
      <div class="deck-body deck-body-center">
        ${context ? `<div class="deck-line" style="text-align:center;margin-bottom:18px">${esc(context)}</div>` : ''}
        <div class="deck-chip-row">
          ${commands.map(c => `<span class="deck-chip" style="border-color:${accent}66;color:${accent}">${esc(c)}</span>`).join('')}
        </div>
        <div class="deck-graph-note">${L(
          'الرسم البياني تفاعلي داخل التطبيق — افتح الشرائح على الشاشة لتحريك المنحنى مباشرة أمام الصف.',
          'The graph is interactive inside the app — open the deck on screen to drag the curve live in front of the class.',
        )}</div>
      </div>
      ${footer(num)}</div>`;
  };

  const challengeSlide = (slide: ActivitySlide, num: number) => {
    const accent = deckSlideAccent('challenge');
    const verifiedBadge = slide.verified ? `
      <div class="deck-verified" style="color:${slide.verifiedBy === 'symbolic' ? '#22C55E' : DECK_MUTED}">
        ${slide.verifiedBy === 'symbolic' ? '🛡️' : '📚'}
        ${slide.verifiedBy === 'symbolic' ? L('تم التحقق من الإجابة رياضيًا (SymPy)', 'Answer symbolically verified (SymPy)') : L('من بنك الأسئلة المُراجَع', 'From the reviewed question bank')}
        ${slide.verifiedBy === 'symbolic' && slide.computedAnswer ? `<div class="deck-evidence">${L('حسبها المُحقِّق مستقلًّا', 'Verifier computed independently')}: ${mathLineToHtml(prettifySymPy(slide.computedAnswer))}</div>` : ''}
      </div>` : '';
    return `<div class="deck-slide">
      <div class="deck-header" style="border-color:${accent}44">
        <span class="deck-emoji">🔐</span>
        <span class="deck-eyebrow" style="color:${accent}">${esc(slide.title)}</span>
      </div>
      <div class="deck-body deck-body-center">
        ${deckContentLine(slide.content, true)}
        ${slide.answer ? `
          <div class="deck-answer" style="border-color:${accent}44">
            <div class="deck-answer-label" style="color:${accent}">${L('الإجابة', 'Answer')}</div>
            <div class="deck-eq">${mathLineToHtml(slide.answer)}</div>
            ${verifiedBadge}
          </div>` : ''}
      </div>
      ${footer(num)}</div>`;
  };

  const mediaSlide = (slide: ActivitySlide, num: number) => {
    const accent = deckSlideAccent(slide.type);
    return `<div class="deck-slide">
      <div class="deck-header" style="border-color:${accent}44">
        <span class="deck-emoji">🖼️</span>
        <span class="deck-eyebrow" style="color:${accent}">${esc(slide.title)}</span>
      </div>
      <div class="deck-body deck-body-center deck-body-media">
        <img class="deck-media-img" src="${esc(slide.mediaUrl ?? '')}" alt="${esc(slide.mediaCaption ?? '')}" />
        ${slide.mediaCaption ? `<div class="deck-media-caption">${esc(slide.mediaCaption)}</div>` : ''}
      </div>
      ${footer(num)}</div>`;
  };

  /**
   * A video can't play in a PDF. Rather than dropping the slide (the teacher
   * would lose the link entirely) or faking a player, this prints the link
   * as a real clickable anchor plus the URL in plain text — so it works both
   * on screen and on paper, where a printed page can only be typed back in.
   */
  const videoSlide = (slide: ActivitySlide, num: number) => {
    const accent = '#B45309';
    const url = slide.mediaUrl ?? '';
    return `<div class="deck-slide">
      <div class="deck-header" style="border-color:${accent}44">
        <span class="deck-emoji">🎬</span>
        <span class="deck-eyebrow" style="color:${accent}">${esc(slide.title)}</span>
      </div>
      <div class="deck-body deck-body-center">
        ${slide.mediaCaption ? `<div class="deck-video-title">${esc(slide.mediaCaption)}</div>` : ''}
        <a class="deck-video-link" style="border-color:${accent}66;color:${accent}" href="${esc(url)}">▶ ${L('شاهد الفيديو', 'Watch the video')}</a>
        <div class="deck-video-url">${esc(url)}</div>
        ${slide.content ? `<div class="deck-video-note">${esc(slide.content)}</div>` : ''}
      </div>
      ${footer(num)}</div>`;
  };

  const contentSlide = (slide: ActivitySlide, num: number) => {
    const accent = deckSlideAccent(slide.type);
    const lines = slide.content.split('\n').filter(Boolean);
    return `<div class="deck-slide">
      <div class="deck-header" style="border-color:${accent}44">
        <span class="deck-emoji">${deckSlideEmoji(slide.type)}</span>
        <span class="deck-eyebrow" style="color:${accent}">${esc(slide.title)}</span>
      </div>
      <div class="deck-body">
        ${lines.map(l => deckContentLine(l, slide.type === 'challenge')).join('')}
      </div>
      ${footer(num)}</div>`;
  };

  const slidesHtml = deck.slides.map((slide, i) => {
    const num = i + 1;
    if (i === 0) return titleSlide(slide, num);
    if (slide.type === 'graph') return graphSlide(slide, num);
    if (slide.type === 'challenge') return challengeSlide(slide, num);
    if (slide.type === 'media' && slide.mediaKind === 'image') return mediaSlide(slide, num);
    if (slide.type === 'media' && slide.mediaKind === 'video') return videoSlide(slide, num);
    if (slide.type === 'divider') return dividerSlide(slide, num);
    return contentSlide(slide, num);
  }).join('\n');

  return `<!DOCTYPE html>
<html dir="${dir}" lang="${isAr ? 'ar' : 'en'}">
<head>
<meta charset="utf-8"/>
<!--
  The app's real typefaces, rather than the generic Arial this used to print
  in. Linked from Google Fonts instead of base64-embedded: the four faces are
  ~440KB, which would sit in the repo AND in every user's JS bundle including
  those who never export. This export already fetches remote images, so it
  already assumes network; with none, the stack below falls back to Arial —
  exactly what it printed before, so offline is no worse than today.

  These being Google Fonts is also what makes a .pptx uploaded to Google
  Slides resolve them (see exportPptx.ts).
-->
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Almarai:wght@400;700&family=Cairo:wght@500;600;700&display=swap" rel="stylesheet"/>
<style>
@page { size: A4 landscape; margin: 0; }
* { box-sizing: border-box; margin: 0; padding: 0; }
/* Almarai carries body copy, Cairo every heavier weight — the same split
   app/_layout.tsx makes for the on-screen UI, so an exported deck reads as
   the same product as the projector. Arial stays as the offline fallback. */
body { font-family: 'Almarai','Arial','Tahoma',sans-serif; background:#1a1a1a; }
.deck-title-badge, .deck-title-main, .deck-divider-title, .deck-eyebrow,
.deck-eq, .deck-answer-label, .deck-chip, .deck-video-link,
.deck-title-meta { font-family: 'Cairo','Arial','Tahoma',sans-serif; }
.deck-slide { width:297mm; height:210mm; background:${DECK_BG}; color:${DECK_TEXT}; position:relative; overflow:hidden; page-break-after:always; display:flex; flex-direction:column; }
.deck-title-slide { background:radial-gradient(circle at 30% 20%, ${DECK_ACCENT}33, transparent 55%), ${DECK_BG}; }
.deck-hero-img { position:absolute; inset:0; width:100%; height:100%; object-fit:cover; z-index:0; }
.deck-hero-gradient { position:absolute; inset:0; z-index:1; background:linear-gradient(180deg, rgba(13,13,20,0.35), rgba(13,13,20,0.92)); }
.deck-title-content { position:relative; z-index:2; flex:1; display:flex; flex-direction:column; align-items:center; justify-content:center; padding:50px; text-align:center; }
.deck-divider-slide { display:flex; flex-direction:column; }
.deck-divider-content { position:relative; z-index:2; flex:1; display:flex; flex-direction:column; align-items:center; justify-content:center; padding:50px; text-align:center; }
.deck-divider-title { font-size:44px; font-weight:700; color:#fff; line-height:1.35; max-width:640px; }
.deck-divider-subtitle { font-size:16px; color:rgba(255,255,255,0.85); margin-top:14px; }
.deck-title-badge { background:${DECK_ACCENT}22; color:#a5b4fc; font-size:12px; letter-spacing:3px; font-weight:700; padding:5px 18px; border-radius:20px; margin-bottom:24px; }
.deck-title-main { font-size:40px; font-weight:700; color:#fff; line-height:1.35; margin-bottom:18px; max-width:560px; }
.deck-title-meta { font-size:15px; color:${DECK_MUTED}; margin-bottom:12px; }
.deck-title-summary { font-size:13px; color:${DECK_MUTED}; max-width:480px; line-height:1.7; }
.deck-header { display:flex; align-items:center; gap:10px; height:64px; flex-shrink:0; padding:0 32px; border-bottom:1.5px solid; }
.deck-emoji { font-size:20px; }
.deck-eyebrow { font-size:16px; font-weight:700; }
.deck-body { flex:1; padding:28px 40px; overflow:hidden; display:flex; flex-direction:column; justify-content:center; gap:10px; }
.deck-body-center { align-items:center; text-align:center; }
.deck-line { font-size:14px; line-height:1.8; color:${DECK_TEXT}; }
.deck-eq { font-size:26px; font-weight:700; color:#fff; text-align:center; line-height:1.6; }
.deck-answer { margin-top:22px; border:1.5px solid; border-radius:12px; padding:16px 24px; background:rgba(255,255,255,0.03); min-width:320px; }
.deck-answer-label { font-size:11px; font-weight:700; letter-spacing:1px; text-transform:uppercase; margin-bottom:8px; }
.deck-verified { margin-top:12px; font-size:11px; font-weight:600; display:flex; flex-direction:column; align-items:center; gap:4px; }
.deck-evidence { font-size:10px; color:${DECK_MUTED}; font-weight:400; }
.deck-chip-row { display:flex; flex-wrap:wrap; justify-content:center; gap:8px; margin-bottom:18px; }
.deck-chip { border:1.5px solid; border-radius:8px; padding:5px 12px; font-size:13px; font-weight:700; }
.deck-graph-note { font-size:11px; color:${DECK_MUTED}; max-width:420px; line-height:1.7; }
.deck-body-media { gap:16px; }
.deck-media-img { max-width:80%; max-height:130mm; object-fit:cover; border-radius:12px; box-shadow:0 8px 30px rgba(0,0,0,0.4); }
.deck-media-caption { font-size:11px; color:${DECK_MUTED}; }
.deck-video-title { font-size:15px; color:${DECK_TEXT}; max-width:520px; line-height:1.6; margin-bottom:20px; }
.deck-video-link { display:inline-block; border:1.5px solid; border-radius:10px; padding:10px 22px; font-size:15px; font-weight:700; text-decoration:none; }
.deck-video-url { font-size:10px; color:${DECK_MUTED}; margin-top:14px; word-break:break-all; max-width:420px; }
.deck-video-note { font-size:11px; color:${DECK_MUTED}; margin-top:12px; }
.deck-footer { position:relative; z-index:2; height:30px; border-top:1px solid rgba(255,255,255,0.08); display:flex; align-items:center; justify-content:space-between; padding:0 32px; flex-shrink:0; }
.deck-footer span { font-size:9px; color:${DECK_MUTED}; }
${MATH_HTML_STYLES}
</style>
</head>
<body>
${slidesHtml}
</body>
</html>`;
}
