/**
 * Plain-text renderings of generated material — what the native share sheet
 * and the clipboard copy hand over, and what the Word export is built from.
 *
 * Split out of `share.ts` for the same reason as `exportHtml.ts`: that file
 * imports `react-native` at module scope, so `node:test` cannot load anything
 * defined beside it. These are pure string builders; the IO stays in
 * `share.ts`, which re-exports them.
 */
import { labelAnswer, labelOptionLine } from './optionLabels.ts';
import { arCountPhrase } from './arCount.ts';
import type {
  ActivityOutput,
  LessonPlanOutput,
  QuizOutput,
  SimplifiedExplanationOutput,
  WorksheetOutput,
} from './ai/AIService.ts';
import type { AttemptResult, CompetencyKey, LevelKey } from './evaluations.ts';

export function formatLessonPlanText(
  plan: LessonPlanOutput,
  title: string,
  meta: { subject: string; grade: string; duration?: number },
  isAr: boolean,
): string {
  const SEP = '═══════════════════════════════';
  const lines: string[] = [];
  const H = (label: string) => `\n${label}\n${'─'.repeat(label.length)}`;

  lines.push(title);
  lines.push(`${meta.subject} | ${meta.grade}${meta.duration ? ` | ${isAr ? arCountPhrase(meta.duration, 'دقيقة', 'دقيقتان', 'دقائق') : `${meta.duration} min`}` : ''}`);
  lines.push(SEP);

  lines.push(H(isAr ? 'الأهداف' : 'Objectives'));
  plan.objectives.forEach(o => lines.push(`• ${o}`));

  lines.push(H(isAr ? 'المواد اللازمة' : 'Materials Needed'));
  plan.materials.forEach(m => lines.push(`• ${m}`));

  if (plan.priorReview?.trim()) {
    lines.push(H(isAr ? 'مراجعة سابقة' : 'Prior Knowledge Review'));
    lines.push(plan.priorReview);
  }

  lines.push(H(isAr ? 'التمهيد' : 'Introduction'));
  lines.push(plan.introduction);

  lines.push(H(isAr ? 'النشاط الرئيسي' : 'Main Activity'));
  lines.push(plan.mainActivity);

  lines.push(H(isAr ? 'التدريب الموجّه' : 'Guided Practice'));
  lines.push(plan.guidedPractice);

  lines.push(H(isAr ? 'التدريب المستقل' : 'Independent Practice'));
  lines.push(plan.independentPractice);

  lines.push(H(isAr ? 'الختام' : 'Closure'));
  lines.push(plan.closure);

  lines.push(H(isAr ? 'التقييم' : 'Assessment'));
  lines.push(plan.assessment);

  lines.push(H(isAr ? 'التمايز' : 'Differentiation'));
  lines.push(plan.differentiation);

  lines.push(H(isAr ? 'الواجب المنزلي' : 'Homework'));
  lines.push(plan.homework);

  lines.push('\n' + SEP);
  lines.push(isAr ? 'أُنشئ بواسطة اقرأ — مساعد التدريس الذكي' : 'Generated by Iqra — AI Teaching Assistant');

  return lines.join('\n');
}

export function formatWorksheetText(
  ws: WorksheetOutput,
  title: string,
  meta: { subject: string; grade: string },
  isAr: boolean,
): string {
  const SEP = '═══════════════════════════════';
  const lines: string[] = [];

  lines.push(title);
  lines.push(`${meta.subject} | ${meta.grade}`);
  lines.push(SEP);
  if (ws.instructions) lines.push(`\n${ws.instructions}\n`);

  let qNum = 1;
  ws.sections.forEach(sec => {
    lines.push(`\n${sec.title.toUpperCase()}`);
    lines.push('─'.repeat(sec.title.length));
    sec.questions.forEach(q => {
      lines.push(`\n${qNum}. ${q.text} (${isAr ? arCountPhrase(q.points, 'نقطة', 'نقطتان', 'نقاط') : `${q.points} pts`})`);
      q.options?.forEach(o => lines.push(`   ○ ${o}`));
      qNum++;
    });
  });

  if (ws.answerKey && ws.answerKey.length > 0) {
    lines.push(`\n${SEP}`);
    lines.push(isAr ? 'مفتاح الإجابات' : 'ANSWER KEY');
    ws.answerKey.forEach(item => lines.push(`${item.num}. ${item.answer}`));
  }

  lines.push('\n' + SEP);
  lines.push(isAr ? 'أُنشئ بواسطة اقرأ — مساعد التدريس الذكي' : 'Generated by Iqra — AI Teaching Assistant');
  return lines.join('\n');
}

export function formatQuizText(
  quiz: QuizOutput,
  title: string,
  meta: { subject: string; grade: string },
  isAr: boolean,
): string {
  const SEP = '═══════════════════════════════';
  const lines: string[] = [];

  lines.push(title);
  lines.push(`${meta.subject} | ${meta.grade}`);
  lines.push(`${isAr ? 'المدة' : 'Duration'}: ${isAr ? arCountPhrase(quiz.duration, 'دقيقة', 'دقيقتان', 'دقائق') : `${quiz.duration} min`} | ${isAr ? 'المجموع' : 'Total'}: ${isAr ? arCountPhrase(quiz.totalPoints, 'نقطة', 'نقطتان', 'نقاط') : `${quiz.totalPoints} pts`}`);
  lines.push(SEP);

  quiz.questions.forEach((q, i) => {
    const typeLabel = q.type === 'multiple_choice'
      ? (isAr ? 'اختيار متعدد' : 'MCQ')
      : q.type === 'true_false'
        ? (isAr ? 'صح/خطأ' : 'T/F')
        : (isAr ? 'قصير' : 'Short');
    lines.push(`\n${i + 1}. [${typeLabel}] ${q.text} (${isAr ? arCountPhrase(q.points, 'نقطة', 'نقطتان', 'نقاط') : `${q.points} pts`})`);
    q.options?.forEach((opt, oi) => lines.push(`   ${labelOptionLine(opt, oi, isAr)}`));
  });

  lines.push(`\n${SEP}`);
  lines.push(isAr ? 'مفتاح الإجابات' : 'ANSWER KEY');
  quiz.questions.forEach((q, i) => {
    lines.push(`${i + 1}. ${labelAnswer(q.options, q.correctAnswer, isAr)}${q.explanation ? ` — ${q.explanation}` : ''}`);
  });

  lines.push('\n' + SEP);
  lines.push(isAr ? 'أُنشئ بواسطة اقرأ — مساعد التدريس الذكي' : 'Generated by Iqra — AI Teaching Assistant');
  return lines.join('\n');
}

// ─── Evaluation result formatter ───────────────────────────────────────────────

const LEVEL_LABEL: Record<LevelKey, { ar: string; en: string }> = {
  beginner: { ar: 'مبتدئ', en: 'Beginner' },
  developing: { ar: 'نامٍ', en: 'Developing' },
  proficient: { ar: 'متمكّن', en: 'Proficient' },
  advanced: { ar: 'متقدّم', en: 'Advanced' },
};
const COMPETENCY_LABEL: Record<CompetencyKey, { ar: string; en: string }> = {
  knowledge: { ar: 'المعرفة', en: 'Knowledge' },
  understanding: { ar: 'الفهم', en: 'Understanding' },
  application: { ar: 'التطبيق', en: 'Application' },
  critical_thinking: { ar: 'التفكير الناقد', en: 'Critical Thinking' },
};
const COMPETENCY_ORDER: CompetencyKey[] = ['knowledge', 'understanding', 'application', 'critical_thinking'];

export function formatAttemptResultText(
  result: AttemptResult,
  studentName: string,
  evaluationTitle: string,
  isAr: boolean,
): string {
  const SEP = '═══════════════════════════════';
  const lines: string[] = [];

  lines.push(evaluationTitle || (isAr ? 'تقييم' : 'Evaluation'));
  lines.push(studentName);
  lines.push(SEP);

  const noMarks = Number(result.totalMarks) <= 0;
  if (noMarks) {
    lines.push(
      isAr
        ? 'لا توجد علامة بعد — كل أسئلة هذا التقييم من نوع يحتاج تصحيحًا يدويًا.'
        : 'No score yet — every question in this evaluation needs manual grading.',
    );
  } else {
    const level = result.levelKey ? LEVEL_LABEL[result.levelKey][isAr ? 'ar' : 'en'] : '—';
    lines.push(`${isAr ? 'المستوى' : 'Level'}: ${level} (${result.percent}%)`);
    lines.push(`${isAr ? 'العلامة' : 'Marks'}: ${result.earnedMarks} / ${result.totalMarks}`);
    if (result.isProvisional) {
      lines.push(
        isAr
          ? 'نتيجة أولية — بعض الأسئلة تحتاج تصحيحًا يدويًا لم يُبنَ بعد.'
          : "Provisional — some questions still need manual grading, which isn't built yet.",
      );
    }

    lines.push('');
    for (const key of COMPETENCY_ORDER) {
      const c = result.competencyScores[key];
      const label = COMPETENCY_LABEL[key][isAr ? 'ar' : 'en'];
      const value = c?.sufficient
        ? `${c.percent}%`
        : isAr ? 'بيانات غير كافية' : 'Not enough evidence';
      lines.push(`${label}: ${value}`);
    }
  }

  lines.push('\n' + SEP);
  lines.push(isAr ? 'أُنشئ بواسطة اقرأ — مساعد التدريس الذكي' : 'Generated by Iqra — AI Teaching Assistant');
  return lines.join('\n');
}

export function formatActivityText(
  activity: ActivityOutput,
  title: string,
  meta: { subject: string; grade: string },
  isAr: boolean,
): string {
  const SEP = '═══════════════════════════════';
  const lines: string[] = [];
  const H = (label: string) => `\n${label}\n${'─'.repeat(label.length)}`;

  lines.push(title);
  lines.push(`${meta.subject} | ${meta.grade} | ${isAr ? arCountPhrase(activity.totalDuration, 'دقيقة', 'دقيقتان', 'دقائق') : `${activity.totalDuration} min`}`);
  lines.push(SEP);

  lines.push(H(isAr ? 'الهدف' : 'Objective'));
  lines.push(activity.objective);

  lines.push(H(isAr ? 'حجم المجموعة' : 'Group Size'));
  lines.push(activity.groupSize);

  lines.push(H(isAr ? 'المواد اللازمة' : 'Materials Needed'));
  activity.materials.forEach(m => lines.push(`• ${m}`));

  lines.push(H(isAr ? 'خطوات النشاط' : 'Activity Steps'));
  activity.steps.forEach(s =>
    lines.push(`${s.stepNumber}. ${s.title} (${s.durationMin} ${isAr ? 'د' : 'min'})\n   ${s.description}`)
  );

  lines.push(H(isAr ? 'نصائح للمعلم' : 'Teacher Tips'));
  activity.teacherTips.forEach(tip => lines.push(`• ${tip}`));

  lines.push(H(isAr ? 'التمايز' : 'Differentiation'));
  lines.push(activity.differentiation);

  lines.push(H(isAr ? 'التقييم' : 'Assessment'));
  lines.push(activity.assessment);

  lines.push('\n' + SEP);
  lines.push(isAr ? 'أُنشئ بواسطة اقرأ — مساعد التدريس الذكي' : 'Generated by Iqra — AI Teaching Assistant');
  return lines.join('\n');
}

/**
 * «تبسيط الشرح» as plain text — the share sheet, the clipboard, the Word export.
 *
 * No objectives, materials or assessment block, unlike `formatLessonPlanText`:
 * this sheet is handed to a student, and those are the teacher's sections.
 * A check whose `answer` is absent prints its question and nothing under
 * «الإجابات» — nothing established that answer, and a blank beats a guess.
 */
export function formatSimplifiedExplanationText(
  out: SimplifiedExplanationOutput,
  title: string,
  meta: { subject: string; grade: string },
  isAr: boolean,
): string {
  const SEP = '═══════════════════════════════';
  const lines: string[] = [];
  const H = (label: string) => `\n${label}\n${'─'.repeat(label.length)}`;

  lines.push(title);
  lines.push(`${meta.subject} | ${meta.grade}`);
  lines.push(SEP);

  lines.push(H(isAr ? 'الفكرة باختصار' : 'The Big Idea'));
  lines.push(out.bigIdea);

  lines.push(H(isAr ? 'الشرح خطوة بخطوة' : 'Step by Step'));
  out.explanation.forEach((s, i) => lines.push(`${i + 1}. ${s}`));

  if (out.keyWords?.length) {
    lines.push(H(isAr ? 'كلمات مفتاحية' : 'Key Words'));
    out.keyWords.forEach(w => lines.push(`• ${w.term}: ${w.meaning}`));
  }

  lines.push(H(isAr ? 'مثال محلول' : 'Worked Example'));
  lines.push(out.workedExample.text);
  out.workedExample.steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
  lines.push(`${isAr ? 'الإجابة:' : 'Answer:'} ${out.workedExample.answer}`);

  lines.push(H(isAr ? 'خطأ شائع' : 'A Common Mistake'));
  lines.push(out.misconception.claim);
  lines.push(out.misconception.correction);

  lines.push(H(isAr ? 'تحقّق من فهمك' : 'Check Your Understanding'));
  out.checks.forEach((c, i) => lines.push(`${i + 1}. ${c.text}`));

  const answered = out.checks
    .map((c, i) => ({ n: i + 1, answer: (c.answer ?? '').trim() }))
    .filter(a => a.answer.length > 0);
  if (answered.length) {
    lines.push(H(isAr ? 'الإجابات' : 'Answers'));
    answered.forEach(a => lines.push(`${a.n}. ${a.answer}`));
  }

  lines.push('\n' + SEP);
  lines.push(isAr ? 'أُنشئ بواسطة اقرأ — مساعد التدريس الذكي' : 'Generated by Iqra — AI Teaching Assistant');

  return lines.join('\n');
}
