/**
 * Export & sharing utilities for Iqra app.
 * Handles: plain-text share, clipboard copy, PDF (expo-print), Word (.docx).
 */

import { Share } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import {
  cacheDirectory,
  moveAsync,
  writeAsStringAsync,
  EncodingType,
} from 'expo-file-system/legacy';

import { LessonPlanOutput, QuizOutput, WorksheetOutput } from '@/services/ai/AIService';

// ─── Plain-text formatters ────────────────────────────────────────────────────

export function formatLessonPlanText(
  plan: LessonPlanOutput,
  title: string,
  meta: { subject: string; grade: string; duration?: number },
  isAr: boolean,
): string {
  const SEP = '═══════════════════════════════';
  const lines: string[] = [];
  const H = (label: string) => `\n${label}\n${'─'.repeat(label.length)}`;

  lines.push(title);
  lines.push(`${meta.subject} | ${meta.grade}${meta.duration ? ` | ${meta.duration} ${isAr ? 'دقيقة' : 'min'}` : ''}`);
  lines.push(SEP);

  lines.push(H(isAr ? 'الأهداف' : 'Objectives'));
  plan.objectives.forEach(o => lines.push(`• ${o}`));

  lines.push(H(isAr ? 'المواد اللازمة' : 'Materials Needed'));
  plan.materials.forEach(m => lines.push(`• ${m}`));

  lines.push(H(isAr ? 'التمهيد' : 'Introduction'));
  lines.push(plan.introduction);

  lines.push(H(isAr ? 'النشاط الرئيسي' : 'Main Activity'));
  lines.push(plan.mainActivity);

  lines.push(H(isAr ? 'التدريب الموجّه' : 'Guided Practice'));
  lines.push(plan.guidedPractice);

  lines.push(H(isAr ? 'التدريب المستقل' : 'Independent Practice'));
  lines.push(plan.independentPractice);

  lines.push(H(isAr ? 'الختام' : 'Closure'));
  lines.push(plan.closure);

  lines.push(H(isAr ? 'التقييم' : 'Assessment'));
  lines.push(plan.assessment);

  lines.push(H(isAr ? 'التمايز' : 'Differentiation'));
  lines.push(plan.differentiation);

  lines.push(H(isAr ? 'الواجب المنزلي' : 'Homework'));
  lines.push(plan.homework);

  lines.push('\n' + SEP);
  lines.push(isAr ? 'أُنشئ بواسطة إقرأ — مساعد التدريس الذكي' : 'Generated by Iqra — AI Teaching Assistant');

  return lines.join('\n');
}

export function formatWorksheetText(
  ws: WorksheetOutput,
  title: string,
  meta: { subject: string; grade: string },
  isAr: boolean,
): string {
  const SEP = '═══════════════════════════════';
  const lines: string[] = [];

  lines.push(title);
  lines.push(`${meta.subject} | ${meta.grade}`);
  lines.push(SEP);
  if (ws.instructions) lines.push(`\n${ws.instructions}\n`);

  let qNum = 1;
  ws.sections.forEach(sec => {
    lines.push(`\n${sec.title.toUpperCase()}`);
    lines.push('─'.repeat(sec.title.length));
    sec.questions.forEach(q => {
      lines.push(`\n${qNum}. ${q.text} (${q.points} ${isAr ? 'نقطة' : 'pts'})`);
      q.options?.forEach(o => lines.push(`   ○ ${o}`));
      qNum++;
    });
  });

  if (ws.answerKey && ws.answerKey.length > 0) {
    lines.push(`\n${SEP}`);
    lines.push(isAr ? 'مفتاح الإجابات' : 'ANSWER KEY');
    ws.answerKey.forEach(item => lines.push(`${item.num}. ${item.answer}`));
  }

  lines.push('\n' + SEP);
  lines.push(isAr ? 'أُنشئ بواسطة إقرأ — مساعد التدريس الذكي' : 'Generated by Iqra — AI Teaching Assistant');
  return lines.join('\n');
}

export function formatQuizText(
  quiz: QuizOutput,
  title: string,
  meta: { subject: string; grade: string },
  isAr: boolean,
): string {
  const SEP = '═══════════════════════════════';
  const lines: string[] = [];

  lines.push(title);
  lines.push(`${meta.subject} | ${meta.grade}`);
  lines.push(`${isAr ? 'المدة' : 'Duration'}: ${quiz.duration} ${isAr ? 'دقيقة' : 'min'} | ${isAr ? 'المجموع' : 'Total'}: ${quiz.totalPoints} ${isAr ? 'نقطة' : 'pts'}`);
  lines.push(SEP);

  quiz.questions.forEach((q, i) => {
    const typeLabel = q.type === 'multiple_choice'
      ? (isAr ? 'اختيار متعدد' : 'MCQ')
      : q.type === 'true_false'
        ? (isAr ? 'صح/خطأ' : 'T/F')
        : (isAr ? 'قصير' : 'Short');
    lines.push(`\n${i + 1}. [${typeLabel}] ${q.text} (${q.points} ${isAr ? 'نقطة' : 'pts'})`);
    q.options?.forEach((opt, oi) => lines.push(`   ${String.fromCharCode(65 + oi)}. ${opt}`));
  });

  lines.push(`\n${SEP}`);
  lines.push(isAr ? 'مفتاح الإجابات' : 'ANSWER KEY');
  quiz.questions.forEach((q, i) => {
    lines.push(`${i + 1}. ${q.correctAnswer}${q.explanation ? ` — ${q.explanation}` : ''}`);
  });

  lines.push('\n' + SEP);
  lines.push(isAr ? 'أُنشئ بواسطة إقرأ — مساعد التدريس الذكي' : 'Generated by Iqra — AI Teaching Assistant');
  return lines.join('\n');
}

// ─── Share as text (native share sheet) ──────────────────────────────────────

export async function shareAsText(text: string, title: string): Promise<void> {
  await Share.share({ message: text, title });
}

// ─── Clipboard ────────────────────────────────────────────────────────────────

export async function copyToClipboard(text: string): Promise<void> {
  await Clipboard.setStringAsync(text);
}

// ─── HTML templates for PDF ──────────────────────────────────────────────────

function htmlBase(content: string, isRTL: boolean, title: string): string {
  const dir = isRTL ? 'rtl' : 'ltr';
  const align = isRTL ? 'right' : 'left';
  return `<!DOCTYPE html>
<html lang="${isRTL ? 'ar' : 'en'}" dir="${dir}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(title)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: ${isRTL ? "'Amiri', 'Noto Naskh Arabic', 'Arabic UI Text', Arial" : "'Inter', 'Helvetica Neue', Arial"}, sans-serif;
      font-size: 14px; line-height: 1.7; color: #1a1a1a;
      padding: 40px; direction: ${dir}; text-align: ${align};
      background: #fff;
    }
    .school-header {
      border-bottom: 2px solid #1B6B62; padding-bottom: 16px; margin-bottom: 24px;
      display: flex; justify-content: space-between; align-items: flex-start;
      flex-direction: ${isRTL ? 'row-reverse' : 'row'};
    }
    .school-name { font-size: 13px; color: #666; }
    .school-placeholder { font-weight: bold; color: #1B6B62; font-size: 15px; }
    .doc-title { font-size: 22px; font-weight: 700; color: #111; margin-bottom: 6px; }
    .doc-meta { font-size: 12px; color: #666; margin-bottom: 24px; }
    .section { margin-bottom: 20px; }
    .section-title {
      font-size: 13px; font-weight: 700; color: #1B6B62;
      text-transform: uppercase; letter-spacing: 0.5px;
      border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin-bottom: 8px;
    }
    .body-text { font-size: 13px; line-height: 1.8; color: #333; }
    ul { padding-${isRTL ? 'right' : 'left'}: 20px; }
    li { margin-bottom: 4px; font-size: 13px; color: #333; }
    .answer-key { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 14px; margin-top: 24px; }
    .answer-key .section-title { color: #15803d; border-color: #bbf7d0; }
    .answer-row { display: flex; flex-direction: ${isRTL ? 'row-reverse' : 'row'}; gap: 8px; margin-bottom: 4px; font-size: 12px; }
    .answer-num { font-weight: 600; color: #15803d; min-width: 24px; }
    .q-card { border: 1px solid #e5e7eb; border-radius: 6px; padding: 12px; margin-bottom: 8px; }
    .q-num { font-weight: 700; color: #1B6B62; }
    .q-option { display: flex; flex-direction: ${isRTL ? 'row-reverse' : 'row'}; gap: 8px; align-items: flex-start; margin-top: 4px; font-size: 12px; color: #555; }
    .q-pts { font-size: 11px; color: #999; margin-top: 4px; }
    .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #aaa; text-align: center; }
  </style>
</head>
<body>
  <div class="school-header">
    <div>
      <div class="school-placeholder">${isRTL ? 'إقرأ — مساعد التدريس الذكي' : 'Iqra — AI Teaching Assistant'}</div>
      <div class="school-name">${isRTL ? 'اسم المدرسة' : 'School Name'}</div>
    </div>
    <div class="school-name">${new Date().toLocaleDateString(isRTL ? 'ar-JO' : 'en-GB')}</div>
  </div>
  ${content}
  <div class="footer">${isRTL ? 'أُنشئ بواسطة إقرأ — مساعد التدريس الذكي' : 'Generated by Iqra — AI Teaching Assistant'}</div>
</body>
</html>`;
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function buildLessonPlanHTML(
  plan: LessonPlanOutput,
  title: string,
  meta: { subject: string; grade: string; duration?: number },
  isAr: boolean,
): string {
  const L = (ar: string, en: string) => isAr ? ar : en;
  const section = (label: string, body: string) =>
    `<div class="section"><div class="section-title">${esc(label)}</div><div class="body-text">${esc(body)}</div></div>`;

  const bullets = (label: string, items: string[]) =>
    `<div class="section"><div class="section-title">${esc(label)}</div><ul>${items.map(i => `<li>${esc(i)}</li>`).join('')}</ul></div>`;

  const content = `
    <div class="doc-title">${esc(title)}</div>
    <div class="doc-meta">${esc(meta.subject)} • ${esc(meta.grade)}${meta.duration ? ` • ${meta.duration} ${L('دقيقة', 'min')}` : ''}</div>
    ${bullets(L('الأهداف', 'Objectives'), plan.objectives)}
    ${bullets(L('المواد اللازمة', 'Materials Needed'), plan.materials)}
    ${section(L('التمهيد', 'Introduction'), plan.introduction)}
    ${section(L('النشاط الرئيسي', 'Main Activity'), plan.mainActivity)}
    ${section(L('التدريب الموجّه', 'Guided Practice'), plan.guidedPractice)}
    ${section(L('التدريب المستقل', 'Independent Practice'), plan.independentPractice)}
    ${section(L('الختام', 'Closure'), plan.closure)}
    ${section(L('التقييم', 'Assessment'), plan.assessment)}
    ${section(L('التمايز', 'Differentiation'), plan.differentiation)}
    ${section(L('الواجب المنزلي', 'Homework'), plan.homework)}
  `;
  return htmlBase(content, isAr, title);
}

export function buildWorksheetHTML(
  ws: WorksheetOutput,
  title: string,
  meta: { subject: string; grade: string },
  isAr: boolean,
): string {
  const L = (ar: string, en: string) => isAr ? ar : en;
  let qNum = 1;
  const sections = ws.sections.map(sec => {
    const questions = sec.questions.map(q => {
      const options = q.options
        ? q.options.map((o, oi) => `<div class="q-option"><span>${String.fromCharCode(65 + oi)}.</span> <span>${esc(o)}</span></div>`).join('')
        : '';
      const html = `<div class="q-card"><span class="q-num">${qNum}.</span> ${esc(q.text)}${options}<div class="q-pts">${q.points} ${L('نقطة', 'pts')}</div></div>`;
      qNum++;
      return html;
    }).join('');
    return `<div class="section"><div class="section-title">${esc(sec.title)}</div>${questions}</div>`;
  }).join('');

  const akRows = ws.answerKey?.map(item =>
    `<div class="answer-row"><span class="answer-num">${item.num}.</span><span>${esc(item.answer)}</span></div>`
  ).join('') ?? '';

  const answerKey = akRows
    ? `<div class="answer-key"><div class="section-title">${L('مفتاح الإجابات', 'Answer Key')}</div>${akRows}</div>`
    : '';

  const content = `
    <div class="doc-title">${esc(title)}</div>
    <div class="doc-meta">${esc(meta.subject)} • ${esc(meta.grade)}</div>
    ${ws.instructions ? `<div class="body-text" style="margin-bottom:16px;color:#555;font-style:italic">${esc(ws.instructions)}</div>` : ''}
    ${sections}
    ${answerKey}
  `;
  return htmlBase(content, isAr, title);
}

export function buildQuizHTML(
  quiz: QuizOutput,
  title: string,
  meta: { subject: string; grade: string },
  isAr: boolean,
): string {
  const L = (ar: string, en: string) => isAr ? ar : en;
  const typeLabel = (t: string) =>
    t === 'multiple_choice' ? L('اختيار متعدد', 'MCQ')
      : t === 'true_false' ? L('صح/خطأ', 'True/False')
        : L('إجابة قصيرة', 'Short Answer');

  const questions = quiz.questions.map((q, i) => {
    const options = q.options
      ? q.options.map((o, oi) => `<div class="q-option"><span>${String.fromCharCode(65 + oi)}.</span> <span>${esc(o)}</span></div>`).join('')
      : '';
    return `<div class="q-card">
      <span class="q-num">${i + 1}.</span>
      <span style="font-size:11px;background:#fef3c7;color:#92400e;padding:2px 7px;border-radius:9px;margin-${isAr ? 'right' : 'left'}:6px">${typeLabel(q.type)}</span>
      ${esc(q.text)}
      ${options}
      <div class="q-pts">${q.points} ${L('نقطة', 'pts')}</div>
    </div>`;
  }).join('');

  const akRows = quiz.questions.map((q, i) =>
    `<div class="answer-row"><span class="answer-num">${i + 1}.</span><span>${esc(q.correctAnswer)}</span></div>`
  ).join('');

  const content = `
    <div class="doc-title">${esc(title)}</div>
    <div class="doc-meta">${esc(meta.subject)} • ${esc(meta.grade)} • ${quiz.duration} ${L('دقيقة', 'min')} • ${quiz.totalPoints} ${L('نقطة', 'pts')}</div>
    ${questions}
    <div class="answer-key"><div class="section-title">${L('مفتاح الإجابات', 'Answer Key')}</div>${akRows}</div>
  `;
  return htmlBase(content, isAr, title);
}

// ─── PDF export ───────────────────────────────────────────────────────────────

export async function exportAsPDF(html: string, filename: string): Promise<void> {
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  // Rename to descriptive filename
  const dest = `${cacheDirectory}${filename}.pdf`;
  await moveAsync({ from: uri, to: dest });
  await Sharing.shareAsync(dest, { mimeType: 'application/pdf', dialogTitle: filename });
}

// ─── Word (.docx) export ──────────────────────────────────────────────────────

export async function exportAsWord(
  text: string,
  filename: string,
  isAr: boolean,
): Promise<void> {
  // Dynamic import to avoid startup cost
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = await import('docx');

  const align = isAr ? AlignmentType.RIGHT : AlignmentType.LEFT;
  const lines = text.split('\n');

  const children = lines.map(line => {
    const trimmed = line.trim();
    if (!trimmed) return new Paragraph({ children: [new TextRun('')] });

    // Section headings (all-caps lines with dash-underline next)
    const isHeading = /^[═─]{5,}$/.test(trimmed);
    if (isHeading) return new Paragraph({ children: [new TextRun({ text: '', break: 1 })] });

    const isSectionHeader = trimmed === trimmed.toUpperCase() && trimmed.length > 3 && !/^[•○]/.test(trimmed) && !/^\d/.test(trimmed);

    if (isSectionHeader && !trimmed.startsWith('═') && !trimmed.startsWith('─')) {
      return new Paragraph({
        heading: HeadingLevel.HEADING_2,
        alignment: align,
        children: [new TextRun({ text: trimmed, bold: true, size: 24 })],
      });
    }

    const isBullet = trimmed.startsWith('•') || trimmed.startsWith('○');
    if (isBullet) {
      return new Paragraph({
        alignment: align,
        bullet: { level: 0 },
        children: [new TextRun({ text: trimmed.replace(/^[•○]\s*/, ''), size: 22 })],
      });
    }

    // First line = title
    const lineIdx = lines.indexOf(line);
    if (lineIdx === 0) {
      return new Paragraph({
        heading: HeadingLevel.HEADING_1,
        alignment: align,
        children: [new TextRun({ text: trimmed, bold: true, size: 32 })],
      });
    }

    return new Paragraph({
      alignment: align,
      children: [new TextRun({ text: trimmed, size: 22 })],
    });
  });

  const doc = new Document({
    sections: [{
      properties: {},
      children,
    }],
  });

  const b64 = await Packer.toBase64String(doc);
  const path = `${cacheDirectory}${filename}.docx`;
  await writeAsStringAsync(path, b64, { encoding: EncodingType.Base64 });
  await Sharing.shareAsync(path, {
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    dialogTitle: filename,
  });
}
