/**
 * Regenerate the wordlist that decides the لا ligature repair.
 *
 * Run: node --experimental-strip-types scripts/build-ligature-wordlist.ts
 *
 * The evidence is the OCR extractions and only those. OCR reads a rendered
 * page, so it never displaces a ligature the way pdf-parse does — measured,
 * not assumed: «السلام», «الصلاة» and «الإسلام» appear 20, 28 and 501 times in
 * OCR output and **zero** times across 735,365 words of pdf-parse text. The
 * defect is total on that side, which is why the corpus cannot police itself
 * and why the list has to come from the other extractor.
 *
 * Two sets come out, and the repair needs both:
 *
 *   correct  — words containing لا, seen at least twice. Licenses a repair:
 *              the لا spelling is a real word *in these books*.
 *   attested — words containing an internal ال, at any count. Blocks a repair:
 *              the ال spelling is real too, so the swap would be a guess.
 *
 * The block set is not a formality. Without it «الثالث» (the third) becomes
 * «الثلاث» and «مثال» (example, 651 occurrences) becomes «مثلا» — 42 forms in
 * all, every one of them a word the books actually meant.
 *
 * The twice-seen floor on `correct` is what separates a real word from an OCR
 * misreading. At a floor of one the list also licenses «طوال» → «طولا» and
 * «خيال» → «خيلا», both of which destroy a correct word on the strength of a
 * single garbled sighting.
 *
 * Rebuild this whenever OCR extractions are added; the list only knows the
 * vocabulary of the books that were OCR'd when it was generated.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const extractedDir = path.join(here, '..', 'src', 'data', 'extracted');
const outFile = path.join(here, '..', 'src', 'data', 'ligature-wordlist.json');

/**
 * Letters and their marks only — the same class `untranspose.ts` tokenises
 * with, and it has to stay the same or a lookup can never match. The whole
 * Arabic block would drag the comma and the Arabic-Indic digits in with it.
 */
const WORD = /[\u0621-\u065F\u0670-\u06D3\u06FA-\u06FF]+/gu;
const MARK = /[ً-ْٰـ]/gu;
const ALEF = 'ا';
const LAM = 'ل';
const MIN_SIGHTINGS = 2;

/** Strip tashkeel and tatweel: the list is keyed on base letters. */
function bare(word: string): string {
  return word.replace(MARK, '');
}

/** Indexes of an internal «ال». Index 0 is the article, handled elsewhere. */
export function internalArticlePositions(word: string): number[] {
  const out: number[] = [];
  for (let i = 1; i < word.length - 1; i++) {
    if (word[i] === ALEF && word[i + 1] === LAM) out.push(i);
  }
  return out;
}

const counts = new Map<string, number>();
let ocrDocs = 0;

for (const file of readdirSync(extractedDir).filter(f => f.endsWith('.json'))) {
  const doc = JSON.parse(readFileSync(path.join(extractedDir, file), 'utf8'));
  if (!Array.isArray(doc.text)) continue;
  if (!String(doc.tool ?? '').includes('tesseract')) continue;
  ocrDocs++;
  for (const page of doc.text) {
    for (const word of String(page.text ?? '').match(WORD) ?? []) {
      const key = bare(word);
      counts.set(key, (counts.get(key) ?? 0) + 1);
    }
  }
}

const correct: string[] = [];
const attested: string[] = [];
for (const [word, n] of counts) {
  if (word.includes(LAM + ALEF) && n >= MIN_SIGHTINGS) correct.push(word);
  if (internalArticlePositions(word).length > 0) attested.push(word);
}
correct.sort();
attested.sort();

writeFileSync(
  outFile,
  JSON.stringify(
    {
      note:
        'Generated by scripts/build-ligature-wordlist.ts from the OCR extractions only. '
        + '`correct` licenses a ligature repair, `attested` blocks one. Do not hand-edit; regenerate.',
      generatedAt: new Date().toISOString().slice(0, 10),
      ocrDocuments: ocrDocs,
      minSightings: MIN_SIGHTINGS,
      correct,
      attested,
    },
    null,
    1,
  ) + '\n',
  'utf8',
);

console.log(`read ${ocrDocs} OCR extractions, ${counts.size} distinct words`);
console.log(`  correct  (licenses a repair): ${correct.length}`);
console.log(`  attested (blocks a repair)  : ${attested.length}`);
console.log(`wrote ${path.relative(process.cwd(), outFile)}`);
