// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/BenchmadeFluencyCatalog-ofS7e3/index.tsx": () => import("../components/mockups/templates/BenchmadeFluencyCatalog-ofS7e3/index.tsx")
};
