/**
 * The invariant that makes the English lesson breakdown derivable.
 *
 * Every book in the Pearson "Jordan High Note" series this repo carries prints
 * one `□ I can …` statement per lesson and exactly 35 per semester, so lesson
 * numbering follows the order of those statements within a unit. The Grade 9
 * files were generated by a script that refused to emit unless every unit
 * yielded exactly seven — but that script lives in a scratchpad and the JSON is
 * what ships, so the invariant is restated here against the committed data.
 *
 * Without this, the claim "35 = 5 units x 7 lessons, verified" is only true of
 * a run nobody can repeat. With it, an edit that drops or duplicates a lesson
 * fails loudly instead of quietly changing what a teacher is shown.
 *
 * Grade 10 English was excluded until 2026-09-10, on the grounds its own
 * provenance_note gave: that its book named the seven slots only by skill
 * banner, so a seven-lesson split would be a guess. It prints the same headers
 * and the same 35 `I can` statements as Grade 9's; the two files now hold the
 * seven lessons a unit, and are covered here for the same reason Grade 9 is.
 * (The four vocational ESP tracks are a different series and genuinely are one
 * lesson per unit — see `g10EnglishVocational.ts`.)
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { nccdG9EngSem1 } from '../catalogs/g9EngSem1.ts';
import { nccdG9EngSem2 } from '../catalogs/g9EngSem2.ts';
import { nccdG10EngSem1 } from '../catalogs/g10EnglishSem1.ts';
import { nccdG10EngSem2 } from '../catalogs/g10EnglishSem2.ts';

/**
 * The fields this invariant is about, and nothing else. Grade 10 English is
 * built by hand rather than through `makeNccdCatalog`, so its lesson type is a
 * different declaration carrying the book's scope-and-sequence columns; the
 * shape below is what the two have in common.
 */
type EngShape = {
  units: Array<{
    number: number;
    lessons: Array<{
      id: string;
      order: number;
      objectives: string[];
      main_idea_ar: string;
    }>;
  }>;
};

const FILES: Array<{ name: string; doc: EngShape; units: number[] }> = [
  { name: 'g9 english S1', doc: nccdG9EngSem1, units: [1, 2, 3, 4, 5] },
  { name: 'g9 english S2', doc: nccdG9EngSem2, units: [6, 7, 8, 9, 10] },
  { name: 'g10 english S1', doc: nccdG10EngSem1, units: [1, 2, 3, 4, 5] },
  { name: 'g10 english S2', doc: nccdG10EngSem2, units: [6, 7, 8, 9, 10] },
];

describe('English lesson shape', () => {
  it('gives every unit exactly seven lessons, numbered 1-7 in order', () => {
    for (const { name, doc, units } of FILES) {
      assert.deepEqual(doc.units.map(u => u.number), units, `${name}: unit numbers`);
      for (const u of doc.units) {
        assert.equal(u.lessons.length, 7, `${name} unit ${u.number}: lesson count`);
        assert.deepEqual(
          u.lessons.map(l => l.order), [1, 2, 3, 4, 5, 6, 7],
          `${name} unit ${u.number}: lesson order`,
        );
        assert.deepEqual(
          u.lessons.map(l => l.id),
          [1, 2, 3, 4, 5, 6, 7].map(n => `u${u.number}_l${n}`),
          `${name} unit ${u.number}: lesson ids`,
        );
      }
    }
  });

  it('carries exactly one printed outcome per lesson, and keeps it in English', () => {
    // The outcome is the book's own sentence. Translating it would change what
    // a teacher is told the lesson delivers, so it stays verbatim — and that
    // is checkable: every one of them starts "I can".
    for (const { name, doc } of FILES) {
      for (const u of doc.units) {
        for (const l of u.lessons) {
          assert.equal(l.objectives.length, 1, `${name} ${l.id}: one outcome`);
          assert.match(l.objectives[0], /^I can .+\.$/, `${name} ${l.id}: outcome text`);
          assert.equal(l.main_idea_ar, l.objectives[0], `${name} ${l.id}: main idea mirrors outcome`);
        }
      }
    }
  });

  it('totals 35 lessons a semester — the count the derivation rested on', () => {
    for (const { name, doc } of FILES) {
      const total = doc.units.reduce((n, u) => n + u.lessons.length, 0);
      assert.equal(total, 35, `${name}: total lessons`);
    }
  });
});
