/**
 * Generates `artifacts/mobile/services/bookFigureAssets.ts`.
 *
 * Metro resolves assets at build time from *static string literals*, so a
 * lookup like `require(figurePath(f))` cannot work — the bundler has no way to
 * know which files to include. The map therefore has to be written out, one
 * literal `require()` per figure.
 *
 * Only figures a lesson actually asks for are emitted. Chemistry's four are
 * skipped along with every unmapped maths figure, because bundling a picture
 * nothing can reach is pure download weight — 63 files on disk, 54 reachable.
 *
 * Run:  node scripts/gen_book_figure_assets.mjs
 * Check: artifacts/mobile/services/__tests__/bookFigureAssets.test.ts fails if
 * this file is stale, so a newly extracted figure cannot be silently missed.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'artifacts/mobile/services/bookFigureAssets.ts');

const read = p => JSON.parse(readFileSync(path.join(ROOT, p), 'utf8'));

const map = read('knowledge-base/figure-lesson-map.json');
const mapped = new Set(
  map.entries.filter(e => e.kbLessonId).map(e => `${e.sourceId}|${e.unit}|${e.lesson}`),
);

const indexes = [
  'knowledge-base/grade-10-math/figures/math-s1-student-book/index.json',
  'knowledge-base/grade-10-math/figures/math-s2-student-book/index.json',
  'knowledge-base/grade-10-chemistry/figures/chem-s1-student-book/index.json',
];

const rows = [];
for (const rel of indexes) {
  const dir = path.dirname(rel);
  for (const f of read(rel).figures) {
    if (!mapped.has(`${f.sourceId}|${f.unit}|${f.lesson}`)) continue;
    rows.push({ key: `${f.sourceId}/${f.file}`, from: `../../../${dir}/${f.file}` });
  }
}
rows.sort((a, b) => a.key.localeCompare(b.key));

const body = rows.map(r => `  '${r.key}': require('${r.from}'),`).join('\n');

writeFileSync(OUT, `/**
 * GENERATED by scripts/gen_book_figure_assets.mjs — do not edit by hand.
 *
 * One static \`require()\` per reachable book figure, because Metro resolves
 * assets from string literals at build time and cannot follow a computed path.
 * Regenerate after extracting figures or editing figure-lesson-map.json.
 */
/* eslint-disable @typescript-eslint/no-require-imports */

/**
 * \`sourceId/file\` → the bundler's handle for that PNG.
 *
 * The two shapes are not interchangeable and both really occur: Metro's web
 * output makes each asset a module exporting \`{uri, width, height}\`, while
 * native \`require()\` yields an opaque numeric id to look up in the asset
 * registry. \`bookFigureUri\` is where that fork is handled.
 */
export type BookFigureAsset = number | { uri: string; width?: number; height?: number };

export const BOOK_FIGURE_ASSETS: Record<string, BookFigureAsset> = {
${body}
};

/** How many figures ship with the app. Asserted by the drift test. */
export const BOOK_FIGURE_COUNT = ${rows.length};
`);

console.log(`wrote ${rows.length} figures → ${path.relative(ROOT, OUT)}`);
